// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package job

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientInfo struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ClientInfo) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Status) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type JobSummarySignal struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	JobId                string   `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	JobName              string   `protobuf:"bytes,3,opt,name=jobName,proto3" json:"jobName,omitempty"`
	Namespace            string   `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	FrameWork            string   `protobuf:"bytes,5,opt,name=frameWork,proto3" json:"frameWork,omitempty"`
	JobStatus            string   `protobuf:"bytes,6,opt,name=jobStatus,proto3" json:"jobStatus,omitempty"`
	Time                 string   `protobuf:"bytes,7,opt,name=time,proto3" json:"time,omitempty"`
	CmIndex              string   `protobuf:"bytes,8,opt,name=cmIndex,proto3" json:"cmIndex,omitempty"`
	Total                string   `protobuf:"bytes,9,opt,name=total,proto3" json:"total,omitempty"`
	HcclJson             string   `protobuf:"bytes,10,opt,name=HcclJson,proto3" json:"HcclJson,omitempty"`
	DeleteTime           string   `protobuf:"bytes,11,opt,name=deleteTime,proto3" json:"deleteTime,omitempty"`
	SharedTorIp          string   `protobuf:"bytes,12,opt,name=sharedTorIp,proto3" json:"sharedTorIp,omitempty"`
	MasterAddr           string   `protobuf:"bytes,13,opt,name=masterAddr,proto3" json:"masterAddr,omitempty"`
	Operator             string   `protobuf:"bytes,14,opt,name=operator,proto3" json:"operator,omitempty"`
	Sid                  string   `protobuf:"bytes,15,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobSummarySignal) Reset()         { *m = JobSummarySignal{} }
func (m *JobSummarySignal) String() string { return proto.CompactTextString(m) }
func (*JobSummarySignal) ProtoMessage()    {}
func (*JobSummarySignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2}
}

func (m *JobSummarySignal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobSummarySignal.Unmarshal(m, b)
}
func (m *JobSummarySignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobSummarySignal.Marshal(b, m, deterministic)
}
func (m *JobSummarySignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobSummarySignal.Merge(m, src)
}
func (m *JobSummarySignal) XXX_Size() int {
	return xxx_messageInfo_JobSummarySignal.Size(m)
}
func (m *JobSummarySignal) XXX_DiscardUnknown() {
	xxx_messageInfo_JobSummarySignal.DiscardUnknown(m)
}

var xxx_messageInfo_JobSummarySignal proto.InternalMessageInfo

func (m *JobSummarySignal) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *JobSummarySignal) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *JobSummarySignal) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *JobSummarySignal) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *JobSummarySignal) GetFrameWork() string {
	if m != nil {
		return m.FrameWork
	}
	return ""
}

func (m *JobSummarySignal) GetJobStatus() string {
	if m != nil {
		return m.JobStatus
	}
	return ""
}

func (m *JobSummarySignal) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *JobSummarySignal) GetCmIndex() string {
	if m != nil {
		return m.CmIndex
	}
	return ""
}

func (m *JobSummarySignal) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func (m *JobSummarySignal) GetHcclJson() string {
	if m != nil {
		return m.HcclJson
	}
	return ""
}

func (m *JobSummarySignal) GetDeleteTime() string {
	if m != nil {
		return m.DeleteTime
	}
	return ""
}

func (m *JobSummarySignal) GetSharedTorIp() string {
	if m != nil {
		return m.SharedTorIp
	}
	return ""
}

func (m *JobSummarySignal) GetMasterAddr() string {
	if m != nil {
		return m.MasterAddr
	}
	return ""
}

func (m *JobSummarySignal) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *JobSummarySignal) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type JobSummarySignalList struct {
	JobSummarySignals    []*JobSummarySignal `protobuf:"bytes,1,rep,name=jobSummarySignals,proto3" json:"jobSummarySignals,omitempty"`
	ReportTime           string              `protobuf:"bytes,2,opt,name=ReportTime,proto3" json:"ReportTime,omitempty"`
	JobTotalNum          int32               `protobuf:"varint,3,opt,name=JobTotalNum,proto3" json:"JobTotalNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *JobSummarySignalList) Reset()         { *m = JobSummarySignalList{} }
func (m *JobSummarySignalList) String() string { return proto.CompactTextString(m) }
func (*JobSummarySignalList) ProtoMessage()    {}
func (*JobSummarySignalList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{3}
}

func (m *JobSummarySignalList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobSummarySignalList.Unmarshal(m, b)
}
func (m *JobSummarySignalList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobSummarySignalList.Marshal(b, m, deterministic)
}
func (m *JobSummarySignalList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobSummarySignalList.Merge(m, src)
}
func (m *JobSummarySignalList) XXX_Size() int {
	return xxx_messageInfo_JobSummarySignalList.Size(m)
}
func (m *JobSummarySignalList) XXX_DiscardUnknown() {
	xxx_messageInfo_JobSummarySignalList.DiscardUnknown(m)
}

var xxx_messageInfo_JobSummarySignalList proto.InternalMessageInfo

func (m *JobSummarySignalList) GetJobSummarySignals() []*JobSummarySignal {
	if m != nil {
		return m.JobSummarySignals
	}
	return nil
}

func (m *JobSummarySignalList) GetReportTime() string {
	if m != nil {
		return m.ReportTime
	}
	return ""
}

func (m *JobSummarySignalList) GetJobTotalNum() int32 {
	if m != nil {
		return m.JobTotalNum
	}
	return 0
}

var fileDescriptor_f32c477d91a04ead = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x6e, 0x48, 0xb3, 0x3f, 0xb3, 0x40, 0x8b, 0x55, 0x24, 0xb7, 0x02, 0xb4, 0xca, 0xa9, 0xe2,
	0xb0, 0x42, 0xe5, 0x08, 0x17, 0xe8, 0x01, 0x76, 0x55, 0x15, 0x29, 0xbb, 0x12, 0x12, 0x37, 0x3b,
	0xf6, 0x96, 0x84, 0x24, 0x13, 0xd9, 0x8e, 0x04, 0x0f, 0x83, 0xc4, 0xfb, 0xf0, 0x52, 0x68, 0xec,
	0xfd, 0xd3, 0x6e, 0xe9, 0x6d, 0xe6, 0x9b, 0x99, 0x6f, 0xbe, 0x99, 0xb1, 0x61, 0x58, 0xa2, 0x9c,
	0xb4, 0x06, 0x1d, 0xb2, 0xb8, 0x44, 0x99, 0xbe, 0x07, 0xb8, 0xae, 0x0a, 0xdd, 0xb8, 0x69, 0xb3,
	0x44, 0xc6, 0xe0, 0xd8, 0x60, 0xa5, 0x79, 0x34, 0x8e, 0x2e, 0x87, 0x99, 0xb7, 0xd9, 0x05, 0x0c,
	0xf2, 0x90, 0xa1, 0x78, 0xec, 0xf1, 0x8d, 0x9f, 0xde, 0x40, 0x6f, 0xee, 0x84, 0xeb, 0x2c, 0x55,
	0xe6, 0xa8, 0x42, 0x65, 0x92, 0x79, 0x9b, 0xb0, 0xa2, 0x59, 0x22, 0x7f, 0x14, 0xd8, 0xc8, 0x7e,
	0x90, 0xed, 0x4f, 0x0c, 0xa7, 0x33, 0x94, 0xf3, 0xae, 0xae, 0x85, 0xf9, 0x35, 0x2f, 0xee, 0x1a,
	0x51, 0x11, 0x49, 0xd7, 0x15, 0x6a, 0x2d, 0x89, 0x6c, 0x76, 0x06, 0x49, 0x89, 0x72, 0xaa, 0x56,
	0xcc, 0xc1, 0x61, 0x1c, 0xfa, 0x25, 0xca, 0x5b, 0x51, 0xeb, 0x15, 0xf3, 0xda, 0x65, 0x2f, 0x60,
	0xd8, 0x88, 0x5a, 0xdb, 0x56, 0xe4, 0x9a, 0x1f, 0xfb, 0xd8, 0x16, 0xa0, 0xe8, 0xd2, 0x88, 0x5a,
	0x7f, 0x45, 0xf3, 0x83, 0x27, 0x21, 0xba, 0x01, 0x28, 0x5a, 0xa2, 0x0c, 0x53, 0xf2, 0x5e, 0x88,
	0x6e, 0x00, 0x52, 0xe7, 0x8a, 0x5a, 0xf3, 0x7e, 0x50, 0x47, 0x36, 0xe9, 0xc8, 0xeb, 0x69, 0xa3,
	0xf4, 0x4f, 0x3e, 0x08, 0x3a, 0x56, 0x2e, 0xe9, 0x76, 0xe8, 0x44, 0xc5, 0x87, 0x41, 0xb7, 0x77,
	0x68, 0x25, 0x9f, 0xf3, 0xbc, 0x9a, 0x59, 0x6c, 0x38, 0x84, 0x95, 0xac, 0x7d, 0xf6, 0x0a, 0x40,
	0xe9, 0x4a, 0x3b, 0xbd, 0xa0, 0x2e, 0x23, 0x1f, 0xdd, 0x41, 0xd8, 0x18, 0x46, 0xf6, 0xbb, 0x30,
	0x5a, 0x2d, 0xd0, 0x4c, 0x5b, 0xfe, 0xd8, 0x27, 0xec, 0x42, 0xc4, 0x50, 0x0b, 0xeb, 0xb4, 0xf9,
	0xa0, 0x94, 0xe1, 0x4f, 0x02, 0xc3, 0x16, 0xa1, 0xee, 0xd8, 0x6a, 0x23, 0x1c, 0x1a, 0xfe, 0x34,
	0x74, 0x5f, 0xfb, 0xec, 0x14, 0x62, 0x5b, 0x28, 0x7e, 0xe2, 0x61, 0x32, 0xd3, 0xdf, 0x11, 0x9c,
	0xed, 0x9f, 0xe8, 0xa6, 0xb0, 0x8e, 0x5d, 0xc3, 0xb3, 0x72, 0x0f, 0xb7, 0x3c, 0x1a, 0xc7, 0x97,
	0xa3, 0xab, 0xe7, 0x13, 0x7a, 0x73, 0xfb, 0x55, 0xd9, 0x61, 0x3e, 0x69, 0xcd, 0x74, 0x8b, 0xc6,
	0xf9, 0x69, 0xc3, 0x71, 0x77, 0x10, 0x9a, 0x76, 0x86, 0x72, 0x41, 0x5b, 0xbb, 0xed, 0x6a, 0x7f,
	0xe5, 0x24, 0xdb, 0x85, 0xae, 0xfe, 0x46, 0x10, 0xcf, 0x50, 0xb2, 0xd7, 0x30, 0xc8, 0xf4, 0x5d,
	0x41, 0x53, 0xb2, 0x13, 0xdf, 0x7f, 0xfb, 0xca, 0x2f, 0x46, 0x1e, 0x08, 0x17, 0x4c, 0x8f, 0xd8,
	0x27, 0x38, 0x9f, 0x77, 0xd2, 0xe6, 0xa6, 0x90, 0xfa, 0xe0, 0xf9, 0x1d, 0x14, 0xdf, 0x3f, 0x4d,
	0x7a, 0xf4, 0x26, 0x62, 0x5f, 0xe0, 0xe5, 0x7f, 0x89, 0xfc, 0x92, 0x0e, 0xc8, 0xce, 0xef, 0x25,
	0xa3, 0x5c, 0x22, 0xfc, 0xd8, 0xff, 0x96, 0x4c, 0xde, 0x95, 0x28, 0x65, 0xcf, 0xff, 0xd8, 0xb7,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xf0, 0x8e, 0xba, 0xbe, 0x03, 0x00, 0x00,
}
